version: '3'
services:
  zookeeper:
    hostname: zookeeper
    platform: linux/amd64
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      - esthete-core-net
  kafka:
    hostname: kafka
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    networks:
      - esthete-core-net
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      #KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafdrop:
    hostname: kafdrop
    platform: linux/amd64
    image: obsidiandynamics/kafdrop
    restart: always
    ports:
      - "9000:9000"
    networks:
      - esthete-core-net
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka
      - zookeeper
networks:
  esthete-core-net: