server:
  port: 8080

spring:
  application:
    name: moongkl-here-mobile-api
  #h2:
  #  console:
  #    enabled: true
  #    path: /h2-console
  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    username: sa
  #    password: sa
  #    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mariadb://${MARIA_HOST}:${MARIA_PORT}/${INITIAL_DB}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${MARIA_USERNAME}
    password: ${MARIA_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
        format_sql: true
    repositories:
      enabled: true
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springfox:
  documentation:
    swagger-ui:
      enabled: true
      base-url: core

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: esthete-s3
      root-directory: test
      photo-directory: photo

    region:
      static: ap-northeast-2
    stack:
      auto: false
    cloudfront:
      distribution-domain: ${CLOUDFRONT_URL}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
