springfox:
  documentation:
    swagger-ui:
      enabled: true
      base-url: core
    swagger:
      v2:
        path: /core
#profile
spring:
  profiles:
    active: dev

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher