# Default values for esthete-user-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# esthete-deployment-chart/values.yaml

replicaCount: 1

image:
  repository: lsb8375/esthete-user-service
  tag: 1.1
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: LoadBalancer
