server:
  port: 8080
  forward-headers-strategy: FRAMEWORK

spring:
  application:
    name: esthete-admin
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_INITIAL_DB}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP-SERVERS}

  jpa:
    defer-datasource-initialization: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_DATASOURCE_DDL-AUTO}
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
        format_sql: true
    repositories:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
    springframework:
      web: DEBUG
      security: DEBUG
      data: DEBUG
      kafka: DEBUG
      hibernate: DEBUG
      jpa: DEBUG
      oauth2: DEBUG
      springframework: DEBUG
      springfox: DEBUG
      esthete: DEBUG
      lombok: DEBUG

springdoc:
  use-fqn: true
  swagger-ui:
    path: /admin/swagger-ui

servers:
  - url: https://api.esthete.roberniro-projects.xyz
    description: Production server

services:
  core-service: ${CORE_SERVICE_URL}

statistics:
  cron-expression: ${CRON_EXPRESSION}
  count-interval-minutes: ${COUNT_INTERVAL_MINUTES}

cors:
  allowed-origin: ${ALLOWED_ORIGIN}

jwt:
  secret: ${JWT_SECRET}
  valid-hours: ${JWT_VALID_HOURS}

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
