# esthete-deployment-chart/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - image: lsb8375/esthete-core:1.2
          imagePullPolicy: IfNotPresent
          name: esthete-core-chart
          env:
            - name: AWS_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: core-config
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: core-config
                  key: AWS_SECRET_KEY
            - name: CLOUDFRONT_URL
              valueFrom:
                configMapKeyRef:
                  name: core-config
                  key: CLOUDFRONT_URL
          ports:
            - containerPort: { { .Values.containerPort } }
