# esthete-deployment-chart/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: AWS_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: core-config
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: core-config
                  key: AWS_SECRET_KEY
            - name: CLOUDFRONT_URL
              valueFrom:
                configMapKeyRef:
                  name: core-config
                  key: CLOUDFRONT_URL
          ports:
            - containerPort: { { .Values.containerPort } }
