# esthete-deployment-chart/templates/deployment.yaml

apiVersion: apps/v1
kind: Service
metadata:
  name: user-service
  namespace: default
spec:
  ports:
    - name: http
      nodePort: 30808
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: mysql
      nodePort: 30069
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: user-service
  sessionAffinity: None
  type: {{ .Values.service.type }}