# esthete-deployment-chart/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: esthete-admin-chart
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
