# esthete-deployment-chart/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
        - name: esthete-core-chart
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef:
                name: core-config
