# esthete-deployment-chart/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}