# esthete-deployment-chart/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          #env:
          #            - name: AWS_ACCESS_KEY
          #              valueFrom:
          #                configMapKeyRef:
          #                  name: user-config
          #                  key: AWS_ACCESS_KEY
          ports:
            - containerPort: { { .Values.containerPort } }
