apiVersion: v1
kind: Service
metadata:
  name: {{ include "esthete-core-chart.fullname" . }}
  labels:
    {{- include "esthete-core-chart.labels" . | nindent 4 }}
  namespace: default
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "esthete-core-chart.selectorLabels" . | nindent 4 }}
